-- Migration: 20260827_seed_bmf_events.sql
-- Description: Seeds initial curated BMF events into public.bmf_events table

INSERT INTO public.bmf_events (
    id,
    title,
    slug,
    tagline,
    description,
    cover_image,
    event_date,
    event_time,
    location_type,
    location_venue,
    location_city,
    category,
    total_capacity,
    registered_count,
    is_published,
    status,
    cta_type,
    external_cta_url,
    external_cta_text,
    pricing_type,
    price_inr,
    requirements,
    tags
)
VALUES
(
    '00000000-0000-0000-0000-000000000001',
    'INNOVEST 3.0 – Startup Demo Day & Investor Conclave',
    'innovest-3-startup-demo-day-cit-chennai-2026',
    'Startup pitches, investor & incubator interactions, live product demos, and funding connections.',
    'Premier Tamil Nadu startup conclave featuring pitches, live demos, mentor feedback, and direct funding/incubation allocations with leading VCs & angel networks. (Registration deadline: 28 August).',
    'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop',
    'September 1–3, 2026',
    '9:30 AM - 5:30 PM IST',
    'in_person',
    'Chennai Institute of Technology',
    'Chennai',
    'Demo Day & Conclave',
    150,
    118,
    true,
    'upcoming',
    'external_link',
    'https://unstop.com/hackathons/innovest-30-innovest-chennai-institute-of-technology-1742335',
    'Apply via Unstop',
    'free',
    0,
    'Founders, Innovators, Angel Investors & Mentors (Registration Deadline: 28 Aug)',
    ARRAY['INNOVEST', 'Chennai', 'CIT', 'Funding', 'Demo Day', 'Pitching']
),
(
    '00000000-0000-0000-0000-000000000002',
    'Startup Founders Meetup by CEDAT',
    'startup-founders-meetup-cedat-bengaluru-sep-2-2026',
    'Collaborative founder meetup for entrepreneurs and MSMEs to exchange feedback and connect with mentors.',
    'A focused, peer-to-peer gathering for early founders, aspiring entrepreneurs, and startup community operators to validate ideas and discover strategic collaborators.',
    'https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=1200&auto=format&fit=crop',
    'September 2, 2026',
    '5:00 PM - 8:00 PM IST',
    'in_person',
    'Koramangala',
    'Bengaluru',
    'Founder Meetup',
    50,
    42,
    true,
    'upcoming',
    'external_link',
    'https://www.cedat.in/events/startup-founders-meetup-by-cedat-2026-09-02-qL5ePx3t9ik7vTqwYupD',
    'Register via CEDAT',
    'free',
    0,
    'Founders, aspiring founders, operators, mentors, and startup-community participants',
    ARRAY['CEDAT', 'Koramangala', 'Bengaluru', 'Founders', 'Networking']
),
(
    '00000000-0000-0000-0000-000000000003',
    'Namma Bengaluru Startups Meetup by CEDAT',
    'namma-bengaluru-startups-meetup-cedat-sep-8-2026',
    'High-energy ecosystem networking for entrepreneurs with active investors and startup enablers.',
    'Connect directly with angel investors, mentors, and ecosystem enablers across Bangalore’s high-growth startup ecosystem.',
    'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1200&auto=format&fit=crop',
    'September 8, 2026',
    '5:30 PM - 8:30 PM IST',
    'in_person',
    'Ashok Nagar',
    'Bengaluru',
    'Ecosystem Mixer',
    60,
    51,
    true,
    'upcoming',
    'external_link',
    'https://www.cedat.in/events/namma-bengaluru-startups-meetup-by-cedat-2026-09-08-GOPiphfsuNwVmZGyIut0',
    'Register via CEDAT',
    'free',
    0,
    'Entrepreneurs and professionals interested in networking with investors, mentors, enablers, and other founders',
    ARRAY['CEDAT', 'Ashok Nagar', 'Bengaluru', 'Investors', 'Enablers']
),
(
    '00000000-0000-0000-0000-000000000004',
    'eChai Startup Demo Day (Chennai Edition)',
    'echai-startup-demo-day-chennai-sep-26-2026',
    'A relaxed, open founder-networking and demo event welcoming early & experienced builders.',
    'Free and open founder meetup requiring no membership fee. Present your product, gain active peer feedback, and connect with fellow builders and angel syndicates.',
    'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?q=80&w=1200&auto=format&fit=crop',
    'September 26, 2026',
    '6:00 PM - 8:00 PM IST',
    'in_person',
    'Chennai Tech Hub & Founder Lounge',
    'Chennai',
    'Startup Demo Day',
    75,
    58,
    true,
    'upcoming',
    'external_link',
    'https://echai.ventures/events/echai-startup-demo-day-in-chennai-sep-26-2026',
    'Register on eChai',
    'free',
    0,
    'Early-stage founders, startup operators, aspiring builders, product teams',
    ARRAY['eChai', 'Demo Day', 'Chennai', 'Networking', 'Open Event']
)
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    tagline = EXCLUDED.tagline,
    description = EXCLUDED.description,
    cover_image = EXCLUDED.cover_image,
    event_date = EXCLUDED.event_date,
    event_time = EXCLUDED.event_time,
    location_type = EXCLUDED.location_type,
    location_venue = EXCLUDED.location_venue,
    location_city = EXCLUDED.location_city,
    category = EXCLUDED.category,
    total_capacity = EXCLUDED.total_capacity,
    is_published = EXCLUDED.is_published,
    status = EXCLUDED.status,
    cta_type = EXCLUDED.cta_type,
    external_cta_url = EXCLUDED.external_cta_url,
    external_cta_text = EXCLUDED.external_cta_text,
    pricing_type = EXCLUDED.pricing_type,
    price_inr = EXCLUDED.price_inr,
    requirements = EXCLUDED.requirements,
    tags = EXCLUDED.tags,
    updated_at = now();
